Repository AY2324S2-CS2113-F14-3/tp, pull requests merged in 2024-03, with the labels that each got.

#26 Add parseInput success test method
  src/test/java/byteceps/commands/ParserTest.java
Labels: to implement

#29 Reworked the framework to create a skeleton
  src/main/java/byteceps/ByteCeps.java
  src/main/java/byteceps/activities/Activity.java
  src/main/java/byteceps/activities/Exercise.java
  src/main/java/byteceps/activities/Workout.java
  src/main/java/byteceps/commands/Command.java
  src/main/java/byteceps/commands/CommandResult.java
  src/main/java/byteceps/commands/ExerciseCommand.java
  src/main/java/byteceps/commands/ExitCommand.java
  src/main/java/byteceps/commands/InputArguments.java
  src/main/java/byteceps/commands/Parser.java
  src/main/java/byteceps/commands/WorkoutCommand.java
  src/main/java/byteceps/errors/Exceptions.java
  src/main/java/byteceps/exercises/Exercise.java
  src/main/java/byteceps/exercises/ExerciseManager.java
  src/main/java/byteceps/processing/ActivityManager.java
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
  src/main/java/byteceps/ui/Ui.java
  src/main/java/byteceps/ui/UserInterface.java
  src/test/java/byteceps/DukeTest.java
  src/test/java/byteceps/commands/ExerciseCommandTest.java
  src/test/java/byteceps/commands/ParserTest.java
  src/test/java/byteceps/processing/ExerciseManagerTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: to implement

#32 Add JUnit Test
  src/main/java/byteceps/processing/WorkoutManager.java
  src/test/java/byteceps/activities/ActivityTest.java
  src/test/java/byteceps/activities/ExerciseTest.java
  src/test/java/byteceps/activities/WorkoutTest.java
Labels: bug, Junit

#33 Add weeklyProgramManager class
  src/main/java/byteceps/ByteCeps.java
  src/main/java/byteceps/activities/Workout.java
  src/main/java/byteceps/commands/Parser.java
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WeeklyProgramManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
Labels: to implement

#36 Add Junit test for WorkoutManager
  src/test/java/byteceps/processing/WorkoutManagerTest.java
Labels: Junit

#38 Delete workout plan
  src/main/java/byteceps/processing/WorkoutManager.java
  src/test/java/byteceps/processing/WorkoutManagerTest.java
Labels: to implement, Junit

#62 Refactor WeeklyProgramManager and Rework HashMap to HashSet
  src/main/java/byteceps/activities/Activity.java
  src/main/java/byteceps/activities/Day.java
  src/main/java/byteceps/processing/ActivityManager.java
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WeeklyProgramManager.java
  src/main/java/byteceps/storage/Storage.java
  src/test/java/byteceps/activities/ActivityTest.java
  src/test/java/byteceps/activities/ExerciseTest.java
  src/test/java/byteceps/activities/WorkoutTest.java
Labels: bug

#65 Bug fix - validate user input for Exercise, Workout
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
  src/test/java/byteceps/processing/ExerciseManagerTest.java
  src/test/java/byteceps/processing/WorkoutManagerTest.java
Labels: bug

#67 Search for exercises & workout plans
  src/main/java/byteceps/processing/ActivityManager.java
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
  src/test/java/byteceps/processing/ExerciseManagerTest.java
  src/test/java/byteceps/processing/WorkoutManagerTest.java
Labels: to implement

#68 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#72 Bug fix for list command
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
Labels: bug

#74 Implement Tracking of Workouts
  src/main/java/byteceps/ByteCeps.java
  src/main/java/byteceps/activities/Exercise.java
  src/main/java/byteceps/activities/TrackedExercise.java
  src/main/java/byteceps/activities/TrackedWorkout.java
  src/main/java/byteceps/activities/Workout.java
  src/main/java/byteceps/commands/Parser.java
  src/main/java/byteceps/processing/ActivityManager.java
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/TrackedWorkoutsManager.java
  src/main/java/byteceps/processing/WeeklyProgramManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
  src/main/java/byteceps/storage/Storage.java
  src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
Labels: to implement

#75 Rename Track to Log and update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ByteCep.puml
  docs/diagrams/WorkoutLog.puml
  docs/diagrams/WorkoutLogOverview.png
  src/main/java/byteceps/ByteCeps.java
  src/main/java/byteceps/activities/ExerciseLog.java
  src/main/java/byteceps/activities/TrackedWorkout.java
  src/main/java/byteceps/activities/WorkoutLog.java
  src/main/java/byteceps/processing/WeeklyProgramManager.java
  src/main/java/byteceps/processing/WorkoutLogsManager.java
  src/main/java/byteceps/storage/Storage.java
  src/main/java/byteceps/ui/UserInterface.java
  src/test/java/byteceps/processing/ExerciseManagerTest.java
  src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
  src/test/java/byteceps/processing/WorkoutManagerTest.java
  text-ui-test/EXPECTED.TXT
Labels: documentation, to implement

#82 Fix log test
  src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
Labels: bug

#79 Add help menu
  src/main/java/byteceps/ByteCeps.java
  src/main/java/byteceps/processing/HelpMenuManager.java
  src/main/java/byteceps/ui/UserInterface.java
  text-ui-test/EXPECTED.TXT
Labels: to implement

#83 SLAP the search method in ActivityManager.
  src/main/java/byteceps/processing/ActivityManager.java
Labels: bug
