Repository AY2324S2-CS2113-F14-3/tp, pull requests merged in 2024-04, with the labels that each got.

#87 Handle corrupted json file
  src/main/java/byteceps/storage/Storage.java
  src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
Labels: bug

#89 Add javadocs
  src/main/java/byteceps/activities/Activity.java
  src/main/java/byteceps/activities/Exercise.java
  src/main/java/byteceps/activities/Workout.java
  src/main/java/byteceps/processing/ActivityManager.java
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
  src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
Labels: documentation

#121 Refine userguide
  docs/UserGuide.md
Labels: documentation

#132 Bug fix for invalid date & future dates
  src/main/java/byteceps/processing/WeeklyProgramManager.java
  src/main/java/byteceps/ui/strings/DayStrings.java
Labels: bug

#134 Bugs fix
  src/main/java/byteceps/activities/Activity.java
  src/main/java/byteceps/activities/Exercise.java
  src/main/java/byteceps/processing/ActivityManager.java
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
  src/test/java/byteceps/activities/ExerciseTest.java
  src/test/java/byteceps/processing/WorkoutManagerTest.java
Labels: bug

#135 Add clearer instruction for program logging
  docs/UserGuide.md
Labels: documentation

#142 Implement edit workout functionality
  docs/UserGuide.md
  src/main/java/byteceps/activities/Workout.java
  src/main/java/byteceps/processing/WorkoutManager.java
  src/main/java/byteceps/ui/strings/ManagerStrings.java
Labels: enhancement

#146 Fix workout lowercase error
  docs/UserGuide.md
  src/main/java/byteceps/processing/WorkoutManager.java
Labels: bug

#149 Add usage message on incomplete commands
  src/main/java/byteceps/ui/strings/ManagerStrings.java
  src/main/java/byteceps/validators/WeeklyProgramValidator.java
Labels: enhancement

#151 Add logging for different weights & reps
  docs/UserGuide.md
  src/main/java/byteceps/activities/ExerciseLog.java
  src/main/java/byteceps/processing/WeeklyProgramManager.java
  src/main/java/byteceps/processing/WorkoutLogsManager.java
  src/main/java/byteceps/storage/Storage.java
  src/main/java/byteceps/ui/strings/ManagerStrings.java
  src/main/java/byteceps/validators/WeeklyProgramValidator.java
  src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
Labels: bug, enhancement

#158 Update both README.md
  README.md
  docs/README.md
  docs/diagrams/banner.jpeg
Labels: documentation

#157 Add PPP
  docs/team/joshualeejunyi.md
Labels: documentation

#153 Add DG & PPP
  data.json.old_20240411_104058
  docs/DeveloperGuide.md
  docs/diagrams/addExercise.png
  docs/diagrams/addExercise.puml
  docs/diagrams/addWorkout.png
  docs/diagrams/addWorkout.puml
  docs/diagrams/assignExercise.png
  docs/diagrams/deleteExercise.png
  docs/diagrams/deleteExercise.puml
  docs/diagrams/deleteWorkout.png
  docs/diagrams/deleteWorkout.puml
  docs/diagrams/editExercise.png
  docs/diagrams/editExercise.puml
  docs/diagrams/exercise.puml
  docs/diagrams/listExercise.png
  docs/diagrams/listExerciseInWorkoutPlan.png
  docs/diagrams/listWorkout.png
  docs/diagrams/listWorkout.puml
  docs/diagrams/searchExercise.puml
  docs/diagrams/searchExercises.png
  docs/diagrams/workout.puml
  docs/plantuml/ActivityClassDiagram.puml
  docs/plantuml/ActivityManagerClassDiagram.puml
  docs/plantuml/ByteCep.puml
  docs/plantuml/WorkoutLog.puml
  docs/plantuml/addExercise.puml
  docs/plantuml/architectureDiagram.puml
  docs/plantuml/assignExercise.puml
  docs/plantuml/deleteWorkout.puml
  docs/plantuml/listExerciseInWorkoutPlan.puml
  docs/team/v4vern.md
Labels: documentation

#163 Clean up DG & add Test cases
  docs/DeveloperGuide.md
  docs/diagrams/addExercise.png
  docs/diagrams/assignExercise.png
  docs/diagrams/deleteWorkout.png
  docs/diagrams/listExerciseInWorkoutPlan.png
  docs/plantuml/addExercise.puml
  docs/plantuml/assignExercise.puml
  docs/plantuml/deleteWorkout.puml
  docs/plantuml/listExerciseInWorkoutPlan.puml
  src/main/java/byteceps/activities/Activity.java
  src/main/java/byteceps/validators/ExerciseValidator.java
  src/test/java/byteceps/activities/ActivityTest.java
  src/test/java/byteceps/activities/ExerciseLogTest.java
  src/test/java/byteceps/activities/WorkoutLogTest.java
  src/test/java/byteceps/activities/WorkoutTest.java
  src/test/java/byteceps/processing/ExerciseManagerTest.java
  src/test/java/byteceps/processing/WorkoutLogsManagerTest.java
  src/test/java/byteceps/processing/WorkoutManagerTest.java
Labels: documentation, Junit

#167 Add test cases, fix bugs & add documentation
  docs/DeveloperGuide.md
  docs/team/v4vern.md
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
  src/main/java/byteceps/ui/UserInterface.java
  src/main/java/byteceps/ui/strings/ManagerStrings.java
  src/main/java/byteceps/validators/ExerciseValidator.java
  src/main/java/byteceps/validators/WorkoutValidator.java
  src/test/java/byteceps/commands/ParserTest.java
  src/test/java/byteceps/processing/CascadingDeletionProcessorTest.java
  src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
  src/test/java/byteceps/ui/UserInterfaceTest.java
Labels: Junit

#170 Update DG for Workout Log + Change PNGs to SVGs + abit more SLAP
  docs/DeveloperGuide.md
  docs/diagrams/ActivityClassDiagram.png
  docs/diagrams/ActivityClassDiagram.svg
  docs/diagrams/ActivityManagerClassDiagram.png
  docs/diagrams/ActivityManagerClassDiagram.svg
  docs/diagrams/WorkoutLogOverview.png
  docs/diagrams/addExercise.png
  docs/diagrams/addExercise.svg
  docs/diagrams/addExerciseLog.png
  docs/diagrams/addExerciseLog.svg
  docs/diagrams/architectureDiagram.png
  docs/diagrams/architectureDiagram.svg
  docs/diagrams/assignExercise.png
  docs/diagrams/assignExercise.svg
  docs/diagrams/assignWorkoutToProgram.png
  docs/diagrams/assignWorkoutToProgram.svg
  docs/diagrams/clearProgram.png
  docs/diagrams/clearProgram.svg
  docs/diagrams/deleteExerciseFromWorkouts.png
  docs/diagrams/deleteExerciseFromWorkouts.svg
  docs/diagrams/deleteWorkout.png
  docs/diagrams/deleteWorkout.svg
  docs/diagrams/deleteWorkoutFromProgram.png
  docs/diagrams/deleteWorkoutFromProgram.svg
  docs/diagrams/helpMenuCommandFormat.png
  docs/diagrams/helpMenuCommandFormat.svg
  docs/diagrams/helpMenuWholeMenu.png
  docs/diagrams/helpMenuWholeMenu.svg
  docs/diagrams/listExerciseInWorkoutPlan.png
  docs/diagrams/listExerciseInWorkoutPlan.svg
  docs/diagrams/loadStorage.png
  docs/diagrams/loadStorage.svg
  docs/diagrams/loadWorkouts.png
  docs/diagrams/loadWorkouts.svg
  docs/diagrams/programToday.png
  docs/diagrams/programToday.svg
  docs/diagrams/saveStorage.png
  docs/diagrams/saveStorage.svg
  docs/diagrams/workoutLog.svg
  docs/plantuml/WorkoutLog.puml
  docs/team/joshualeejunyi.md
  docs/team/pqienso.md
  docs/team/v4vern.md
  src/main/java/byteceps/processing/WeeklyProgramManager.java
  src/main/java/byteceps/processing/WorkoutLogsManager.java
  src/main/java/byteceps/validators/WeeklyProgramValidator.java
  src/main/java/byteceps/validators/WorkoutLogsValidator.java
Labels: documentation, enhancement

#172 Fix crash from listing history after deleting workout
  src/main/java/byteceps/processing/WeeklyProgramManager.java
Labels: bug

#173 Clean up documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#175 Fixes the 31 feb bugs
  src/main/java/byteceps/storage/Storage.java
Labels: bug

#179 Update DG with TOC and remove duplicate section
  docs/DeveloperGuide.md
Labels: documentation

#177 Fix duplicate exercise log bug + WorkoutLogsValidatorTest
  docs/UserGuide.md
  src/main/java/byteceps/ByteCeps.java
  src/main/java/byteceps/activities/WorkoutLog.java
  src/main/java/byteceps/errors/Exceptions.java
  src/main/java/byteceps/processing/ActivityManager.java
  src/main/java/byteceps/processing/CascadingDeletionProcessor.java
  src/main/java/byteceps/processing/ExerciseManager.java
  src/main/java/byteceps/processing/WeeklyProgramManager.java
  src/main/java/byteceps/processing/WorkoutLogsManager.java
  src/main/java/byteceps/processing/WorkoutManager.java
  src/main/java/byteceps/storage/Storage.java
  src/main/java/byteceps/ui/UserInterface.java
  src/main/java/byteceps/ui/strings/ManagerStrings.java
  src/main/java/byteceps/validators/WorkoutLogsValidator.java
  src/test/java/byteceps/processing/CascadingDeletionProcessorTest.java
  src/test/java/byteceps/processing/ExerciseManagerTest.java
  src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
  src/test/java/byteceps/processing/WorkoutLogsManagerTest.java
  src/test/java/byteceps/processing/WorkoutManagerTest.java
  src/test/java/byteceps/ui/UserInterfaceTest.java
  src/test/java/byteceps/validators/WorkoutLogsValidatorTest.java
Labels: bug, Junit

#182 Add check if action parameter for list is empty
  src/main/java/byteceps/ui/strings/ManagerStrings.java
  src/main/java/byteceps/validators/Validator.java
Labels: bug

#186 Attempt to fix DG format
  docs/DeveloperGuide.md
Labels: bug, documentation

#185 Remove unused strings
  src/main/java/byteceps/ui/strings/DayStrings.java
  src/main/java/byteceps/ui/strings/ManagerStrings.java
  src/main/java/byteceps/ui/strings/StorageStrings.java
Labels: enhancement

#187 Fix dg format
  docs/DeveloperGuide.md
Labels: documentation

#189 Fix PPP links in AboutUs.md
  docs/AboutUs.md
Labels: documentation

#190 Update UG
  docs/team/joshualeejunyi.md
Labels: documentation

#191 Display UML
  docs/team/joshualeejunyi.md
Labels: documentation

#192 Add check for extra slashes
  src/main/java/byteceps/ByteCeps.java
  src/main/java/byteceps/commands/Parser.java
  src/main/java/byteceps/ui/strings/UiStrings.java
  src/test/java/byteceps/commands/ParserTest.java
  src/test/java/byteceps/processing/CascadingDeletionProcessorTest.java
  src/test/java/byteceps/processing/ExerciseManagerTest.java
  src/test/java/byteceps/processing/HelpMenuManagerTest.java
  src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
  src/test/java/byteceps/processing/WorkoutManagerTest.java
  src/test/java/byteceps/validators/HelpValidatorTest.java
Labels: bug

#196 Remove loc line
  docs/team/joshualeejunyi.md
Labels: documentation

#206 Edit UG introduction
  docs/UserGuide.md
Labels: documentation

#211 Change heading format
  docs/team/joshualeejunyi.md
Labels: documentation

#213 Add key UG grammar corrections
  docs/UserGuide.md
Labels: documentation
